VideoGameStore/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from VideoGameStore import settings
from accounts.views import ProfileDetailView, SubmittableLoginView, user_logout, SignUpView, profile_redirect, \
  ProfileBiographyUpdateView
from viewer.views import *

urlpatterns = [
  path('admin/', admin.site.urls, name='admin'),
  path('', home, name='home'),


  path('genres/', GenresListView.as_view(), name="genres"),
  path('genre/create/', GenreCreateView.as_view(), name="genre_create"),
  path('genre/<int:pk>/', GenreDetailView.as_view(), name="genre"),
  path('genre/<int:pk>/update/', GenreUpdateView.as_view(), name="genre_edit"),

  path('games/', GamesListView.as_view(), name="games"),
  path('game/create/', GameCreateView.as_view(), name='game_create'),
  path('game/<int:pk>/', game, name="game"),
  path('game/<int:pk>/update', GameUpdateView.as_view(), name="game_edit"),

  path('profile/', profile_redirect),
  path('profile/<int:pk>/update_bio', ProfileBiographyUpdateView.as_view(), name='profilebio_update'),
  path('profile/<int:pk>/', ProfileDetailView.as_view(), name='profile'),

  path('accounts/', include('django.contrib.auth.urls')),
  path('accounts/login/', SubmittableLoginView.as_view(), name='login'),
  path('accounts/logout/', user_logout, name='logout'),
  path('accounts/signup/', SignUpView.as_view(), name='signup'),

  path('buy/<int:pk>', buy, name="buy_game"),
  path('buy_confirm/<int:pk>', buy_confirm, name="buy_confirm"),

  path('publisher/<int:pk>/', PublisherDetailView.as_view(), name="publisher"),
  path('publisher/<int:pk>/update', PublisherUpdateView.as_view(), name="pub_edit"),
  path('publisher/create/', PublisherCreateView.as_view(), name="pub_create"),
  path('developer/<int:pk>/', DeveloperDetailView.as_view(), name="developer"),
  path('developer/<int:pk>/update', DeveloperUpdateView.as_view(), name="dev_edit"),
  path('developer/create/', DeveloperCreateView.as_view(), name="dev_create"),

  path('images/', ImageListView.as_view(), name='images'),
  path('image/<int:pk>/', ImageDetailView.as_view(), name='image'),
  path('image/create/', ImageCreateView.as_view(), name='img_add'),
  path('image/update/<int:pk>/', ImageUpdateView.as_view(), name='img_edit'),
  path('image/delete/<int:pk>/', ImageDeleteView.as_view(), name='img_del'),

  path('search/', search, name='search'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

viewer/models.py
from django.db import models
from django.db.models import Model, CharField, ManyToManyField, FloatField, DateTimeField, TextField, DateField, \
    URLField, SET_NULL, ForeignKey, ImageField, DecimalField


# Create your models here.
class Genre(Model):
    name = CharField(max_length=100, null=False, blank=False, unique=True)
    description = TextField(null=True, blank=True)

    class Meta:
        ordering = ['name']

    def __repr__(self):
        return f"Genre(name={self.name})"

    def __str__(self):
        return self.name

class Developer(Model):
    name = CharField(max_length=100, null=False, blank=False, unique=True)
    website = URLField(null=False, blank=True)
    about = TextField(null=True, blank=True)

    class Meta:
        ordering = ['name']

    def __repr__(self):
        return f"Developer(name={self.name})"

    def __str__(self):
        return self.name


class Publisher(Model):
    name = CharField(max_length=100, null=False, blank=False, unique=True)
    website = URLField(null=False, blank=True)
    about = TextField(null=True, blank=True)

    class Meta:
        ordering = ['name']

    def __repr__(self):
        return f"Publisher(name={self.name})"

    def __str__(self):
        return self.name



class Game(Model):
    name = CharField(max_length=100, null=False, blank=False, unique=True)
    genres = ManyToManyField(Genre, blank=True, related_name='games')
    price = DecimalField(max_digits=6, decimal_places=2, null=False, blank=False)
    developers = ManyToManyField(Developer, blank=True, related_name='games')
    publishers = ManyToManyField(Publisher, blank=True, related_name='games')
    release_date = DateField()
    description = TextField(null=True, blank=True)
    system_reqs = TextField(null=False, blank=False)
    updated = DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']

    def __repr__(self):
        return f"Game(name={self.name})"

    def __str__(self):
        return self.name




class Image(Model):
    image = ImageField(upload_to='images/', default=None, null=False, blank=False)
    game = ForeignKey(Game, on_delete=SET_NULL, null=True, blank=True, related_name='image')
    description = TextField(null=True, blank=True)

    def __repr__(self):
        return f"Description(description={self.description})"

    def __str__(self):
        return self.description[:25]

templates/base.html
{% load static %}

<div style="min-height:100vh;display: flex; flex-direction: column;">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet"
              href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
              integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
              crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
                integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
                crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
                integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
                crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
                integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
                crossorigin="anonymous"></script>
    </head>

    <body style="background-color:black;color: white">

    {% include "navbar.html" %}

    <div class="container" >
        <div class="jumbotron" style="background-color:#2d2d2d;" >
            {% block content %}{% endblock %}
        </div>
    </div>



    </body>
    {% include "footer.html" %}
</div>

templates/footer.html
<footer class="text-center text-white bg-dark p-4" style="margin-top:auto">
    NotSteam Estore -
    Final Project -
    by Patrik Závodník
</footer>

templates/form.html
{% extends "base.html" %}

{% block title %}
    NotSteam Estore
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <table>{{ form.as_table }}</table>
        <input type="submit" id="id_submit" value="Confirm" class="btn btn-primary" style="background-color:black;border:none;">
    </form>
{% endblock %}

templates/form_image.html
{% extends "base.html" %}

{% block title %}
    Adding files
{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" id="id_submit" value="Submit" class="btn btn-primary" style="background-color:grey;border:none">
    </form>
{% endblock %}

templates/navbar.html
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'home' %}" style="margin-top:-9px">NotSteam</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
        <a class="nav-item nav-link active" href="{% url 'games' %}">Games</a>
        <a class="nav-item nav-link active" href="{% url 'genres' %}">Genres</a>
        {% if user.is_superuser %}
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarAdminAddLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color:black">
            Add New
            </a>

            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            {% if perms.viewer.add_game %}
                <a class="dropdown-item" href="{% url 'game_create' %}">Add Game</a>
            {% endif %}
            {% if perms.viewer.add_genre %}
                <a class="dropdown-item" href="{% url 'genre_create' %}">Add Genre</a>
            {% endif %}
            {% if perms.viewer.add_pub %}
                <a class="dropdown-item" href="{% url 'pub_create' %}">Add Publisher</a>
            {% endif %}
            {% if perms.viewer.add_dev %}
                <a class="dropdown-item" href="{% url 'dev_create' %}">Add Developer</a>
            {% endif %}
            </div>
        </li>
        <div class="navbar-nav">
            <a class="nav-item nav-link active" href="http://127.0.0.1:8000/admin/"> Admin Site</a>
            <a class="nav-item nav-link active" href="{% url 'images' %}">Images</a>
        </div>
        {% endif %}
        <div class="navbar-nav ml-auto">
            <div class="search-div">
                <form method="post" action="/search/">
                    {% csrf_token %}
                    <input type="text" id="search" name="search" style="margin-top:5px;margin-bottom:-5px;margin-left:10px" placeholder="Search...">
                </form>
            </div>
        </div>

    </ul>
        <div class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
            <div class="navbar-nav">
                <a class="nav-item nav-link active" href="{% url 'profile' user.id %}">{{user.username}}</a>
            </div>
            <div class="navbar-nav">
                <form action="{% url 'logout' %}" method="post">
                    {% csrf_token %}
                <button type="submit" class="btn btn-light" style="margin-bottom: -15px; padding-top: 7px">Logout</button>
                </form>
            </div>
            {% else %}
            <div class="navbar-nav">
            <a href="{% url 'signup' %}">
                <button type="button" class="btn btn-light" >Register</button>
            </a>
            <a href="{% url 'login' %}">
                <button type="button" class="btn btn-light" >Login</button>
            </a>
            </div>
            {% endif %}
        </div>


<!--      <div class="navbar-nav">-->
<!--        <div class="nav-item dropdown">-->
<!--          {% if user.is_authenticated %}-->
<!--            <a class="nav-link active dropdown-toggle" href="#" data-toggle="dropdown">{{ user.username }}</a>-->
<!--            <div class="dropdown-menu dropdown-menu-end">-->
<!--                <a class="dropdown-item" href="{% url 'profile' user.id %}">Profil</a>-->
<!--                <form action="{% url 'logout' %}" method="post">-->
<!--                    {% csrf_token %}-->
<!--                <button type="submit" class="btn btn-light">Logout</button>-->
<!--                </form>-->
<!--                <a class="dropdown-item" href="{% url 'password_change' %}">Změna hesla</a>-->
<!--            </div>-->
<!--          {% else %}-->
<!--            <a class="nav-link active dropdown-toggle" href="#" data-toggle="dropdown">Nepřihlášený uživatel</a>-->
<!--            <div class="dropdown-menu">-->
<!--                <a class="dropdown-item" href="{% url 'login' %}">Přihlásit</a>-->
<!--                <a class="dropdown-item" href="{% url 'signup' %}">Registrace</a>-->
<!--                <a class="dropdown-item" href="{% url 'password_reset' %}">Reset hesla</a>-->
<!--            </div>-->
<!--          {% endif %}-->
<!--        </div>-->
<!--      </div>-->
  </div>
</nav>